name: Go Build
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      org_name:
        required: true
        type: string
    secrets:
      gcp_token:
        required: true
      go_token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node ${{ inputs.jdk }}
    steps:
      - uses: actions/checkout@v2

      - name: Private Go Module
        run: |
          git config --global url."https://${{ secrets.go_token }}:x-oauth-basic@github.com/${{ inputs.org_name }}".insteadOf "https://github.com/${{ inputs.org_name }}"

      - uses: imjasonh/setup-ko@v0.6

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: '1.20.8'
          kustomize: '4.4.1'
          skaffold: '1.36.0'

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.project }}
          service_account_key: ${{ secrets.gcp_token }}
          export_default_credentials: true

      - name: Google GCR Auth
        run: gcloud auth configure-docker --quiet
        
      - name: Install Deps
        run: yarn install

      - name: Publish
        run: skaffold build --file-output=artifact.json

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifact.json
