name: Node Build
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: number
      project:
        required: true
        type: string
    secrets:
      gcp_token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ inputs.jdk }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.version }}
          registry-url: "https://npm.pkg.github.com"

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: '1.20.8'
          kustomize: '4.4.1'
          skaffold: '1.36.0'

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.project }}
          service_account_key: ${{ secrets.gcp_token }}
          export_default_credentials: true

      - name: Google GCR Auth
        run: gcloud auth configure-docker --quiet

      - name: Publish
        run: skaffold build --file-output=artifact.json

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifact.json
